### PR TITLE
Small improvements in README and ServerInitialisation

### PR DESCRIPTION
**Pull request by kaspergrubbe**
Let me know what you think

### CODE REVIEW

**Comment by aquasync** [comment]
Looks good. My preference though would be not to change markup but rather rename to README.rdoc as I include that text as part of the built documentation (cf http://www.rubydoc.info/gems/ruby-vnc/). That's sufficient for github to at least format it nicely (see eg https://github.com/aquasync/ruby-ole).

**Comment by kaspergrubbe** [comment]
Did not know a lot about .rdoc, but you were right, it works! 👍

**Comment by kaspergrubbe** [comment]
Hi @aquasync 

Could you merge this? Or is anything else wrong?

**Comment by kaspergrubbe** [comment]
PR lives on here: https://github.com/aquasync/ruby-vnc/pull/6

**Pull request closed without merging**
