### PR TITLE
Rubocop style fixes

### PR DESCRIPTION
**Pull request by kaspergrubbe**
Small fixes, mostly it is changing the tabs to spaces, `.freeze` some strings, and use `'` instead of `"` for strings where interpolation or byte-sequences is not used. 

It was done running Rubocop with default rules: `rubocop --auto-gen-config --auto-correct`

### CODE REVIEW

**Comment by kaspergrubbe** [comment]
@aquasync Hey, did you see this?

**Comment by aquasync** [comment]
Hi, yeah not really a big fan cause it's hard to go through - would prefer a no-op change like whitespace to be separate. Not familiar with rubocop, but stuff like changing `=begin`/`=end` comments to a whole bunch of `#` prefixed lines just makes for unnecessary churn. Seems like you've got a better solution for testing anyway (ie using an actual vnc server). Some is changing auto-generated files (eg spec_helper), and I'm not sure I buy into the need to freeze all the constant strings.

Let me know if you feel more strongly about this, but would rather pass.

**Comment by kaspergrubbe** [comment]
Hi @aquasync, thanks for getting back to me :-) 

Sorry if my PR was hard to review, basically I was just running Rubucop in its automatic fix-mode, so sorry for the low-effort pull-request.

I agree with some of your points, mostly the changes was done to shut up Robucop, and so that I could introduce it to run with RSpec without tweaking the setup too much without failing.

- I don't mind the `=begin`/`=end` comments staying, this is going to be changed soon anyway I only kept it around as a reference.

- Freezing was definitely a bit aggressive, the only place it made sense was in `version.rb`.

I have converted the changes that I think made sense into individual commits, so that it will be easier to review, and to understand the change that was made and why. 

Let me know what you think.

**Comment by kaspergrubbe** [comment]
@aquasync Hey buddy, did you have a chance to look at these changes? Do I need to do anything? 

These style changes are a bit of a blocker for my continued work since I want to introduce version handling (for different versions of supported VNC versions) and I would prefer not having to battle merges with different indentation.

**Comment by aquasync** [comment]
Sorry, yeah looks fine to me.

**Pull request merged**
